# Full project: https://gitlab.com/pages/plain-html

image: node:lts-slim

stages:
  - build
  - test
  - deploy

cache:
  paths:
  - app/node_modules/

build:
  stage: build
  only:
  - master
  script:
  - chown -R node:node .
  - cd app
  - yarn
  - yarn build
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
    - ./app
    expire_in: 2 days

test:
  stage: test
  only:
  - master
  script:
  - cd app
  - yarn test

deploy:
  stage: deploy
  only:
  - master
  image: ubuntu:latest
  before_script:
  - apt-get update -y
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install openssh-client -y)'
  - eval `ssh-agent -s`
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -p "$PORT" "$SERVER_IP" >> ~/.ssh/know_hosts
  - ssh-keyscan -p "$PORT" "$SERVER_DOMAIN" >> ~/.ssh/know_hosts
  - chmod 644 ~/.ssh/know_hosts
  - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
  - ssh -o StrictHostKeyChecking=no -p "$PORT" "$USER_AND_DOMAIN" "$CLEAN_OLD_CODE"
  script:
  - cd app
  - scp -P "$PORT" -r .nuxt "$SERVER_ADDRESS"
  - scp -P "$PORT" -r lang "$SERVER_ADDRESS"
  - scp -P "$PORT" -r server "$SERVER_ADDRESS"
  - scp -P "$PORT" -r static "$SERVER_ADDRESS"
  - scp -P "$PORT" -r store "$SERVER_ADDRESS"
  - scp -P "$PORT" i18n.config.js "$SERVER_ADDRESS"
  - scp -P "$PORT" nuxt.config.js "$SERVER_ADDRESS"
  - scp -P "$PORT" package.json "$SERVER_ADDRESS"
  - scp -P "$PORT" yarn.lock "$SERVER_ADDRESS"
  - ssh -o StrictHostKeyChecking=no -p "$PORT" "$USER_AND_DOMAIN" "$DEPLOY_COMMAND"
