# Full project: https://gitlab.com/pages/plain-html

image: node:lts-slim

stages:
  - build
  - test
  - deploy

cache:
  paths:
  - app/node_modules/

build:
  stage: build
  only:
  - master
  script:
  - chown -R node:node .
  - cd app
  - yarn
  - yarn build

test:
  stage: test
  only:
  - master
  script:
  - cd app
  - yarn test

deploy:
  stage: deploy
  only:
  - master
  before_script:
  - apt-get update -y
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install openssh-client -y)'
  - eval `ssh-agent -s`
  - mkdir -p ~/.ssh && chmod 700 ~/.ssh
  - touch ~/.ssh/know_hosts
  - ssh-keyscan -t -p 7459 rsa $SERVER_DOMAIN >> ~/.ssh/know_hosts && chmod 644 ~/.ssh/know_hosts
  - cat ~/.ssh/know_hosts
  - ssh-add <(echo $SSH_PRIVATE_KEY | base64 --decode)
  - ssh -T -p 7459 $SERVER_DOMAIN
  script:
  - cd app
  - mkdir dist
  - yarn generate
  - scp -P 7459 -r dist/. $SERVER_ADDRESS
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
    - ./app/dist
    expire_in: 2 days
