# Full project: https://gitlab.com/pages/plain-html

image: node:lts-slim

stages:
  - build
  - test
  - deploy

cache:
  paths:
  - app/node_modules/

build:
  stage: build
  only:
  - master
  script:
  - chown -R node:node .
  - cd app
  - yarn
  - yarn build

test:
  stage: test
  only:
  - master
  script:
  - cd app
  - yarn test

deploy:
  stage: deploy
  only:
  - master
  before_script:
  - apt-get update -qq -y
  - apt-get install -qq git -y
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client -y)'
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - ssh-add < ~/.ssh/id_rsa
  - chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
  - ssh $SERVER_IP -tt -p 7459
  script:
  - cd app
  - mkdir dist
  - yarn generate
  - scp -P 7459 -r dist/. $SERVER_ADDRESS
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
    - ./app/dist
    expire_in: 2 days
